version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27000:27000"
    volumes:
      - ./mongo-data:/opt/app
    command: --wiredTigerCacheSizeGB=1.5
  top.api:
    image: top-api:latest
    container_name: top-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/opt/app/.env
